### ISSUE TITLE
Error when installing - SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by JoeyAbsi** [chuot/rc-scanner#23]
I am trying to install rc-scanner on Ubuntu but I'm getting this error:
``Building client app...
> rc-scanner-client@0.10.3 build
> ng build --base-href ./ --configuration production

✔ Browser application bundle generation complete.
✔ Copying assets complete.
✔ Index html generation complete.
✔ Service worker generation complete.

Initial Chunk Files           | Names         |  Raw Size | Estimated Transfer Size
main.744010dbd4a1885a.js      | main          | 274.33 kB |                68.04 kB
styles.bffbb93370ba1ac9.css   | styles        |  72.42 kB |                 7.48 kB
polyfills.4a84457d02bc33fa.js | polyfills     |  44.50 kB |                13.54 kB
runtime.499407861cd0ca2a.js   | runtime       |   1.05 kB |               600 bytes

                              | Initial Total | 392.29 kB |                89.65 kB

Build at: 2022-03-12T23:42:59.769Z - Hash: ff6dc5cf8fd2c8b5 - Time: 9090ms
 done
file:///home/pi/rc-scanner/server/lib/rc-scanner/config.js:29
            deviceId: typeof config?.audio?.deviceId === 'number'
                                    ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)

An error has occured. Please re-run the command like this: 'DEBUG=true node run.js'
``

I did try running it using `DEBUG=true node run.js` but I still am getting this error.

I did install all the prerequisites.

**Comment by chuot** [comment]
Your NodeJs version seems too old. Make sure it is at least LTS or higher as per the instructions.

**Comment by JoeyAbsi** [comment]
Yep, I had v12. I installed v17.7.1 and ran the update.js script to rebuild the directory. I did need to add sudo to be able to access the device: `sudo node run.js`

I am now getting this error:
`node: src/hostapi/alsa/pa_linux_alsa.c:3636: PaAlsaStreamComponent_BeginPolling: Assertion `ret == self->nfds' failed.
Aborted (core dumped)


An error has occured. Please re-run the command like this: 'DEBUG=true node run.js'`

**Comment by chuot** [comment]
You shouldn't had to sudo for the app to work, but maybe something is wrong with your files permissions.

The latest error looks like pulseaudio isn't installed on your linux. Which distro/flavor is it?
