### ISSUE TITLE
Error when installing: Cannot find module

### ISSUE THREAD

**Issue by ofadam** [chuot/rc-scanner#30]
I'm getting the following error when trying to set up rc-scanner for the first time under Ubuntu 20 with the latest version of NodeJS LTS. Is this a path issue?

node:internal/modules/cjs/loader:1029
  throw err;
  ^

Error: Cannot find module '/usr/local/bin/rc-scanner/debug'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Module._load (node:internal/modules/cjs/loader:872:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v19.1.0

**Comment by chuot** [comment]
It seems that some packages used by Rc Scanner aren't yet compatible with NodeJS 19.X, which is not LTS btw.

Rc Scanner is scheduled for a facelift in early 2023 with new features. In the meantime, please use NodeJS 18 LTS. I just tried on a new Ubuntu 20.04 desktop with a minimal install and it worked for me.

**Comment by ofadam** [comment]
That did the trick, thanks!
